MAJOR refactor; preparing for implementation of makefile

diff --git a/lib/configure b/lib/configure
--- a/lib/configure
+++ b/lib/configure
@@ -1,33 +1,23 @@
 #!/usr/bin/env sh
 
-recursive_ln() (
-	SRC="$(readlink -f "$1")"
-	DEST="$2"
+# !! NON-POSIX feature available in BSD, GNU/Linux and MacOS: options -s and -v of "cp"
+# Not used, since MacOS 14.1 has a bug where the "-s" option does not work as expected.
+rlink() (
+	set -- "$(realpath "$1")" "$2" # use absolute path as link source
 
-	if [ -d "$SRC" ]; then
-		NEW_DEST="$DEST/$(basename "$SRC")"
-		mkdir -p "$NEW_DEST"
+	if [ ! -d "$1" ]; then printf "Creating symlink: "; ln -sfv "$1" "$2"; return 0; fi
 
-		ls -1A "$SRC" | while read -r SRC_ITEM
-			do recursive_ln "$SRC/$SRC_ITEM" "$NEW_DEST"; done
-	else
-		ln -sf "$SRC" "$DEST"
-	fi
+	if [ ! -r "$1" ]; then printf "[rlink] error: cannot read link source directory: $1\n" >&2; exit 1; fi
+
+	mkdir -p "$2"
+
+	for ITEM in $(ls -1AL "$1"); do
+		if [ ! -d "$1/$ITEM" ]; then printf "Creating symlink: "; ln -sfv "$1/$ITEM" "$2"; continue; fi
+		rlink "$1/$ITEM" "$2/$ITEM"
+	done
 )
 
-DATA_DIR="$CONFMAN_REPO/$PKG/data"
-
-if [ -d "$DATA_DIR" ] && [ -r "$DATA_DIR" ]; then
-	mkdir -p "$CONFMAN_DEST"
-
-	while read CONFIG; do
-		# !! NON-POSIX feature available in BSD, GNU/Linux and MacOS: options -s and -v for command "cp"
-		# Disabled, since MacOS 14.1 has a bug with the "cp" utility where the "-s" option does not work as expected
-		#cp -Rsv "$DATA_DIR/$CONFIG" "$HOME"
-
-		recursive_ln "$DATA_DIR/$CONFIG" "$CONFMAN_DEST"
-	done <<-EOF
-	$(ls -1A "$DATA_DIR")
-	EOF
-fi
+SRC_DIR="${SRC_DIR-$CONFMAN_REPO/$PKG/data}"
+LINK_TARGET="${LINK_TARGET-$CONFMAN_DEST}"
+if [ -d "$SRC_DIR" ]; then rlink "$SRC_DIR" "$LINK_TARGET"; fi
 
diff --git a/lib/unconfigure b/lib/unconfigure
--- a/lib/unconfigure
+++ b/lib/unconfigure
@@ -1,35 +1,40 @@
 #!/usr/bin/env sh
 
-recursive_unlink() (
-	SRC="$(readlink -f "$1")"
-	DEST="$2"
-	CONFIG_NAME="$(basename "$SRC")"
+delink() (
+	safe_unlink () {
+		if [ ! -e "$2" ]; then return 0; fi
+		if [ -d "$1" ] || [ ! -L "$2" ] || [ "$1" != "$(realpath "$2")" ]; then
+			printf '[delink] error: link source does not match link target\n\tsource: %s\n\ttarget: %s\n\t%s\n' "$1" "$2" >&2
+			exit 1
+		fi
+		printf 'Removing symlink: '
+		rm -fv "$2"
+	}
 
-	if [ -d "$SRC" ]; then
-		NEW_DEST="$DEST/$CONFIG_NAME"
+	set -- "$(realpath "$1")" "$2" # use absolute path as link source
 
-		ls -1A "$SRC" | while read -r SRC_ITEM; do
-			recursive_unlink "$SRC/$SRC_ITEM" "$NEW_DEST"
-		done
-	else
-		# Remove config file at destination dir
-		echo "Removing config data at: $DEST/$CONFIG_NAME"
-		rm -f "$DEST/$CONFIG_NAME"
-	fi
+	# [Case 1] $1:source --> file (symlink origin), $2:target --> file (symlink)
+	if [ ! -d "$2" ]; then safe_unlink "$1" "$2"; return; fi
 
-	# Delete destination dir if it exists and if empty after removing config file
-	# The destination dir might not exist in the first place. (e.g. the config data was never installed, etc.)
-	if [ -d "$DEST" ] && [ -z "$(ls -A "$DEST")" ]; then
-		echo "Removing empty target config dir at: $DEST"
-		rmdir "$DEST"
+	# [Case 2] $1:source --> file (symlink origin), $2:target --> dir (parent of symlink)
+	if [ ! -d "$1" ]; then safe_unlink "$1" "$2/$(basename "$1")"; return; fi
+
+	# [Case 3] $1:source --> dir (parent of symlink origin), $2:target --> dir (parent of symlink)
+	if [ ! -r "$1" ]; then printf "[delink] error: cannot read link source directory: $1\n" >&2; exit 1; fi
+	for ITEM in $(ls -1AL "$1"); do
+		if [ ! -d "$1/$ITEM" ]; then
+			safe_unlink "$1/$ITEM" "$2/$ITEM"
+		else
+			delink "$1/$ITEM" "$2/$ITEM"
+		fi
+	done
+	if [ -z "$(ls -1AL "$2")" ]; then
+		printf "Removing empty directory: "
+		rm -fdv "$2"
 	fi
 )
 
-DATA_DIR="$CONFMAN_REPO/$PKG/data"
-
-if [ -d "$DATA_DIR" ]; then
-	ls -1A "$DATA_DIR" | while read CONFIG; do
-		recursive_unlink "$DATA_DIR/$CONFIG" "$CONFMAN_DEST"
-	done
-fi
+SRC_DIR="${SRC_DIR-$CONFMAN_REPO/$PKG/data}"
+LINK_TARGET="${LINK_TARGET-$CONFMAN_DEST}"
+if [ -d "$SRC_DIR" ]; then delink "$SRC_DIR" "$LINK_TARGET"; fi
 
