Added new pkg 'neovim'. Added 'update' script for 'NvChad'.
- Added new pkg 'neovim'. The pkg dir contains a placeholder file
  '.gitkeep' to force git to track the dir.
- Added a 'update' script to pkg 'NvChad'. Execute it from the 'dots'
  repository root to pull the 'NvChad' upstream commits into the
  'packages/NvChad/data' subtree path.
- Small modification to 'install' script for 'nvm' to make parts of it
  easily reusable for other scripts.

diff --git a/packages/nvm/install b/packages/nvm/install
--- a/packages/nvm/install
+++ b/packages/nvm/install
@@ -1,13 +1,13 @@
 #!/usr/bin/env sh
 
-if command -v git >/dev/null; then
-	git clone https://github.com/nvm-sh/nvm.git "$HOME/.nvm"
-	cd "$HOME/.nvm"
-	git checkout master
-	git checkout $(git describe --tags --abbrev=0)
-	. nvm.sh
-else
-	printf "ERROR: failed to install 'nvm' for unable to locate utility 'git'." >&2
+if ! command -v git >/dev/null; then
+	printf "ERROR: failed to install '$PKG' for unable to locate utility 'git'." >&2
 	exit 1
 fi
+
+git clone https://github.com/nvm-sh/nvm.git "$HOME/.nvm"
+cd "$HOME/.nvm"
+git checkout master
+git checkout $(git describe --tags --abbrev=0)
+. nvm.sh
 
